# Generated by Django 3.2.16 on 2024-08-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20240812_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
